services:
  floci:
    image: floci/floci:latest
    container_name: jose-data-lab-floci
    ports:
      - "4566:4566"
    environment:
      FLOCI_STORAGE_MODE: memory
      FLOCI_HOSTNAME: floci
      FLOCI_SERVICES_DUCK_URL: http://floci-duck:3000
      FLOCI_SERVICES_ATHENA_DUCK_URL: http://floci-duck:3000

  floci-duck:
    image: floci/floci-duck:latest
    container_name: jose-data-lab-floci-duck
    ports:
      - "3000:3000"

  pipeline:
    build:
      context: .
      dockerfile: local/Dockerfile
    container_name: jose-data-lab-pipeline
    depends_on:
      - floci
      - floci-duck
    environment:
      AWS_ENDPOINT_URL: http://floci:4566
      AWS_DEFAULT_REGION: us-east-1
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      LAB_BUCKET: jose-data-engineering-lab-local
      GLUE_DATABASE: jose_data_engineering_lab_db
    volumes:
      - .:/app
    command: ["python", "local/run_local_pipeline.py"]
